variables:
  PROJECT_NAME: element-web
  IMAGE_PREFIX: qxcr.io/dtd
  ALPHA_NAMESPACE: matrix

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
    - alpha
  script: 
  - export REACT_SDK_REPO=git@git.internal.yunify.com:dtd/matrix-react-sdk.git -w
  - export REACT_SDK_REPO=master
  - export JS_SDK_REPO=git@git.internal.yunify.com:dtd/matrix-js-sdk.git
  - export JS_SDK_BRANCH=master
  - export USE_CUSTOM_SDKS=true
  - dos2unix scripts/docker-link-repos.sh && bash scripts/docker-link-repos.sh
  - yarn --network-timeout=100000 install
  - dos2unix scripts/docker-package.sh && bash scripts/docker-package.sh
  - IMAGE_TAG="v$(date "+%Y%m%d")-$(git rev-parse --short HEAD)"
  - docker build -f Dockerfile.ci -t "$IMAGE_PREFIX/$PROJECT_NAME:$IMAGE_TAG" .
  - docker push "$IMAGE_PREFIX/$PROJECT_NAME:$IMAGE_TAG"