variables:
  PROJECT_NAME: element-web
  IMAGE_PREFIX: qxcr.io/dtd
  ALPHA_NAMESPACE: matrix
  ENV: "REACT_SDK_REPO=git@git.internal.yunify.com:dtd/matrix-react-sdk.git REACT_SDK_REPO=master JS_SDK_REPO=git@git.internal.yunify.com:dtd/matrix-js-sdk.git JS_SDK_BRANCH=master  USE_CUSTOM_SDKS=true"


before_script:
  - mkdir src-tmp
  - mv $(ls |grep -v src-tmp) src-tmp/
  - mv  src-tmp src

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
    - alpha
  script: 
  - $ENV dos2unix src/scripts/docker-link-repos.sh && bash src/scripts/docker-link-repos.sh
  - yarn --network-timeout=100000 install
  - dos2unix src/scripts/docker-package.sh && bash src/scripts/docker-package.sh
  - IMAGE_TAG="v$(date "+%Y%m%d")-$(git rev-parse --short HEAD)"
  - docker build -f Dockerfile.ci -t "$IMAGE_PREFIX/$PROJECT_NAME:$IMAGE_TAG" .
  - docker push "$IMAGE_PREFIX/$PROJECT_NAME:$IMAGE_TAG"